system_info:
  system_id: null
  num_site: 100
  bulk_id: "mp-866108"
  bulk_symbol: "Hf2Zn6"
  ads_smiles: "*OCHCH3"
  miller: (1, 1, 0)
  shift: 0.12
  top: true
  source_system_id: "custom_exp_19"
